### ISSUE TITLE
Burn bootloader

### ISSUE THREAD

**Issue by liudr** [watterott/ATmega328PB-Testing#14]
This may be very obvious to you but could you explain how you would burn bootloader either making it behave like a 328P or a 328PB? It would be very nice to have this step detailed in readme.

What I do is I load the bootloader hex onto an sd card and use Nick Gammon's hex uploader to do the burning:

https://github.com/nickgammon/arduino_sketches/tree/master/Atmega_Hex_Uploader

I also have a separate setup for DIP chips, with an old version of westfw's optiloader. It seems that he had added support to treat PB as P:

https://github.com/WestfW/OptiLoader/blob/master/optiLoader.ino

Both methods burn a lot faster than using Arduino IDE's "Burn bootloader" option.

Any advice what to do to put either P or PB bootloader is greatly appreciated!

**Comment by awatterott** [comment]
It is possible to use a 328PB bootloader on 328P and vice versa, because the devices are hardware compatible. The difference between both bootloaders is only the signature bytes.
If you choose in the Arduino IDE as board one from this board package, then with *Burn Bootloader*
 the bootloader for 328PB will be flashed and if you want a 328P bootloader then you can choose as board *Arduino Uno*.
The 328PB bootloader hex file can also be found [here](https://github.com/watterott/ATmega328PB-Testing/tree/master/hardware/atmega328pb/avr/bootloaders).
